# Generated by Django 3.2.6 on 2021-08-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('surename', models.CharField(max_length=250)),
                ('fathername', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('write_date', models.DateField()),
                ('description', models.CharField(max_length=4000)),
                ('pages', models.IntegerField()),
                ('image', models.ImageField(upload_to='books/%y/%m/%d')),
            ],
        ),
    ]
