# Generated by Django 3.2.6 on 2021-08-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fathername',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
