# Generated by Django 3.2.6 on 2021-08-19 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_autor_fathername'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='autor_relative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.autor', verbose_name='Автор произведения'),
        ),
    ]
